{% set name = "sweetviz" %}
{% set version = "2.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sweetviz-{{ version }}.tar.gz
  sha256: 219a595da31195ca99977e08ef09eca482abaaa639da97cf79a84691da3cef8c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    # imports itself on setup.py so we need all of these here :-(
    - importlib_resources >=1.2.0
    - jinja2 >=2.11.1
    - matplotlib-base >=3.1.3
    - numpy >=1.16.0
    - pandas >=0.25.3,!=1.0.0,!=1.0.1,!=1.0.2
    - scipy >=1.3.2
    - tqdm >=4.43.0
  run:
    - python >=3.6
    - importlib_resources >=1.2.0
    - jinja2 >=2.11.1
    - matplotlib-base >=3.1.3
    - numpy >=1.16.0
    - pandas >=0.25.3,!=1.0.0,!=1.0.1,!=1.0.2
    - scipy >=1.3.2
    - tqdm >=4.43.0

test:
  imports:
    - sweetviz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fbdesignpro/sweetviz
  summary: A pandas-based library to visualize and compare datasets.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
