{% set name = "sweetviz" %}
{% set version = "2.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sweetviz-{{ version }}.tar.gz
  sha256: 076bcab57835db167789e68949340f074dee2da78a24eaaaf211d2735f38b691

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - setuptools >=61
    - pip
  run:
    - python >=3.8
    - pandas >=0.25.3,!=1.0.0,!=1.0.1,!=1.0.2
    - numpy >=1.16.0
    - matplotlib-base >=3.1.3
    - tqdm >=4.43.0
    - scipy >=1.3.2
    - jinja2 >=2.11.1
    - importlib-resources >=1.2.0

test:
  imports:
    - sweetviz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fbdesignpro/sweetviz
  summary: A pandas-based library to visualize and compare datasets.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
